swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  # Base path
  /people:
    # All CRUD operations at that path can be specified below (like get, post, put, delete)
    get:
      # Which python function should this route map to
      operationId: "people.read"
      tags:
        - "People"
      # Describe what this operation does
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      # Describe the response structure
      responses:
        # Status code
        200:
          description: "Successful read people list operation"
          # response schema
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
    post:
      operationId: "people.create"
      tags:
        - "People"
      summary: "Create a person and add it to the people list"
      description: "Create a new person in the people list"
      # If passing a body, describe the parameters that would be passed
      parameters:
        - name: person
          # Where is the param passed: body, query or path params
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of person to create
              lname:
                type: string
                description: Last name of person to create
      responses:
        201:
          description: Successfully created person in list
  /people/{lname}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: Read one person from the people list
      description: Read one person from the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string
    put:
      operationId: people.update
      tags:
        - People
      summary: Update a person in person list
      description: Update a person in the people list
      parameters:
        - name: lname
          in: path
          description: Last name of the person to update in the list
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties: 
              fname: 
                type: string
              lname:
                type: string
      responses:
        200:
          description: Successfully updated the person in people list

